In [1]:
# Initial imports
import numpy as np
import pandas as pd
# import hvplot.pandas
from pathlib import Path
# import plotly.express as px
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.decomposition import PCA
from sklearn.cluster import KMeans

In [8]:
# import Final_project_NYC_BIKE_LANE_cleaned.csv data to match accident site 
file_path = "Resources/Segment2/Final_Project_NYC_CRASH_LANE_xDATABASE.csv"
CL_df= pd.read_csv(file_path, index_col=0 )
print(CL_df.shape)
CL_df

(9193, 21)

,COLLISION_ID,DATES,TIME,BOROUGH,ZIP CODE,LATITUDE,LONGITUDE,NUMBER OF PERSONS INJURED,NUMBER OF PERSONS KILLED,NUMBER OF PEDESTRIANS INJURED,...,NUMBER OF CYCLIST INJURED,NUMBER OF CYCLIST KILLED,NUMBER OF MOTORIST INJURED,NUMBER OF MOTORIST KILLED,CONTRIBUTING FACTOR VEHICLE 1,CONTRIBUTING FACTOR VEHICLE 2,VEHICLE TYPE CODE 1,VEHICLE TYPE CODE 2,STREET,BIKE_LANE
0,4271563,1/2/20,13:00:00,MANHATTAN,10003,40.714165,-74.006320,1,0,0,...,1,0,0,0,Driver Inattention/Distraction,Unspecified,sedan,Bike,CHAMBERS STREET,1
1,4268322,1/2/20,16:00:00,MANHATTAN,10012,40.725643,-73.992070,1,0,0,...,1,0,0,0,Turning Improperly,Unspecified,sedan,Bike,BOWERY,1
2,4268207,1/2/20,17:00:00,BROOKLYN,11221,40.693874,-73.917770,1,0,0,...,1,0,0,0,Traffic Control Disregarded,Unspecified,station wagon/sport utility vehicle,Bike,CENTRAL AVENUE,0
3,4268408,1/3/20,8:00:00,BRONX,10456,40.820747,-73.906006,1,0,0,...,1,0,0,0,Driver Inattention/Distraction,Unspecified,e-bike,Taxi,JACKSON AVENUE,0
4,4269187,1/3/20,11:00:00,BROOKLYN,11205,40.691017,-73.954475,1,0,0,...,1,0,0,0,View Obstructed/Limited,Unsafe Speed,sedan,E-Bike,DE KALB AVENUE,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9188,4571618,10/9/22,1:00:00,QUEENS,11375,40.734295,-73.850310,1,0,0,...,1,0,0,0,Traffic Control Disregarded,Unspecified,taxi,Bike,108 STREET,0
9189,4571590,10/9/22,6:00:00,BROOKLYN,11201,40.689840,-73.978630,1,0,0,...,1,0,0,0,Failure to Yield Right-of-Way,Unspecified,bike,Station Wagon/Sport Utility Vehicle,DE KALB AVENUE,1
9190,4571393,10/9/22,11:00:00,BROOKLYN,11201,40.702610,-73.992516,1,0,0,...,1,0,0,0,Driver Inattention/Distraction,Pedestrian/Bicyclist/Other Pedestrian Error/Co...,bike,Bike,FRONT STREET,1
9191,4571698,10/9/22,12:00:00,MANHATTAN,10002,40.715080,-73.992500,1,0,0,...,1,0,0,0,Turning Improperly,Unspecified,bike,Station Wagon/Sport Utility Vehicle,CANAL STREET,1
9192,4571553,10/9/22,20:00:00,BROOKLYN,11223,40.600590,-73.961370,1,0,0,...,1,0,0,0,Failure to Yield Right-of-Way,Unspecified,sedan,Bike,AVENUE T,0

In [9]:
CWL_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 9193 entries, 0 to 9192
Data columns (total 21 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   COLLISION_ID                   9193 non-null   int64
 1   DATES                          9193 non-null   object
 2   TIME                           9193 non-null   object
 3   BOROUGH                        9192 non-null   object
 4   ZIP CODE                       9193 non-null   int64
 5   LATITUDE                       9193 non-null   float64
 6   LONGITUDE                      9193 non-null   float64
 7   NUMBER OF PERSONS INJURED      9193 non-null   int64
 8   NUMBER OF PERSONS KILLED       9193 non-null   int64
 9   NUMBER OF PEDESTRIANS INJURED  9193 non-null   int64
 10  NUMBER OF PEDESTRIANS KILLED   9193 non-null   int64
 11  NUMBER OF CYCLIST INJURED      9193 non-null   int64
 12  NUMBER OF CYCLIST KILLED       9193 non-null   int64
 13  NUMBER OF MOTORIST INJURED     9193 non-null   int64
 14  NUMBER OF MOTORIST KILLED      9193 non-null   int64
 15  CONTRIBUTING FACTOR VEHICLE 1  9193 non-null   object
 16  CONTRIBUTING FACTOR VEHICLE 2  9193 non-null   object
 17  VEHICLE TYPE CODE 1            9193 non-null   object
 18  VEHICLE TYPE CODE 2            9193 non-null   object
 19  STREET                         9193 non-null   object
 20  BIKE_LANE                      9193 non-null   int64
dtypes: float64(2), int64(11), object(8)
memory usage: 1.5+ MB

In [10]:
# import Final_project_NYC_BIKE_LANE_cleaned.csv data to match accident site 
file_path = "Resources/Segment2/Final_project_NYC_WEATHER_xDATABASE.csv"
WEATHER = pd.read_csv(file_path, index_col=0 )
print(WEATHER.shape)
WEATHER.head(10)

(9193, 7)

    DATES      TIME   TEMP  VISIBILITY  HUMIDITY  WIND_SPEED WEATHER_MAIN
0  1/2/20  13:00:00  33.94     10000.0        61        9.17        Clear
1  1/2/20  16:00:00  42.03     10000.0        54        9.17        Clear
2  1/2/20  17:00:00  44.60     10000.0        48       12.75         Rain
3  1/3/20   8:00:00  46.78     10000.0        60        8.05         Rain
4  1/3/20  11:00:00  44.92     10000.0        74        8.05         Rain
5  1/3/20  13:00:00  44.37     10000.0        81        9.17         Rain
6  1/4/20   2:00:00  47.43     10000.0        81        5.82         Rain
7  1/5/20   9:00:00  39.42     10000.0        57       28.86       Clouds
8  1/5/20  14:00:00  39.02     10000.0        53       34.45       Clouds
9  1/6/20  19:00:00  43.83     10000.0        53       19.69       Clouds

In [11]:
WEATHER.info(10)

<class 'pandas.core.frame.DataFrame'>
Int64Index: 9193 entries, 0 to 9192
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   DATES         9193 non-null   object
 1   TIME          9193 non-null   object
 2   TEMP          9193 non-null   float64
 3   VISIBILITY    9180 non-null   float64
 4   HUMIDITY      9193 non-null   int64
 5   WIND_SPEED    9193 non-null   float64
 6   WEATHER_MAIN  9193 non-null   object
dtypes: float64(3), int64(1), object(3)
memory usage: 574.6+ KB